version: "3.7"

networks:
    shares:
        driver: bridge

services:
    auth:
        build:
            context: .
            dockerfile: ./Auth/API/Dockerfile
        ports:
            - "5500:5500"
        environment:
            - "PORT=5500"
        networks:
            - shares

    users:
        build:
            context: .
            dockerfile: ./Shares.Users/Dockerfile
        ports:
            - "5501:5501"
        environment:
            - "PORT=5501"
        networks:
            - shares

    orders:
        build:
            context: .
            dockerfile: ./Orders/API/Dockerfile
        ports:
            - "5503:5503"
        environment:
            - "PORT=5503"
        networks:
            - shares

    api:
        build:
            context: .
            dockerfile: ./Shares.Web/Dockerfile
        ports:
            - "5502:80"
        depends_on:
            - auth
            - users
        networks:
            - shares
